### ISSUE TITLE
Releaseの実装

### ISSUE THREAD

**Issue by ranhai613** [AyKo/ftl-multiverse-japanese-patch#2]
自分は定期的に日本語化パッチの更新をしていきたいと思います。つきましては、バージョン管理をするためReleaseを実装していただけると嬉しいです。参考までに自分が作ったものが[こちら](https://github.com/ranhai613/ftl-multiverse-japanese-patch/releases)です。

**Comment by AyKo** [comment]
だいぶ遅くなってしまいまいましたが、やってみました。ありがとうございます！

**Comment by ranhai613** [comment]
ご対応ありがとうございますm(_ _)m FTL日本語WikiのリンクをRelease に差し替えておきます！
